@startuml

entity Category

Category : uuid id 
Category : string name 
Category : string description 
Category : boolean is_active 
Category : date created_at 

Category : create()
Category : update()
Category : activate()
Category : deactivate()
Category : delete()

@enduml